name: auto-run-with-time

run-name: ${{ github.actor }} learning setup auto run with time in GitHub Actions

on:
  schedule:
    - cron: '30 18 * * *'
  push:
    
jobs:
  auto-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Now is 1:30 am"
